Update to holochain v25 + updated anchor code from Clutter
holochain/cointoss pull request #4
Opened 2018-05-29 19:57 UTC by ddd-mtl

#45
https://waffle.io/holochain/org/cards/5b0c036ca2f2bc001b6b91f5

2018-05-29 20:55 UTC, zippy requested changes
Great work, besides those two requests, I think it's ready to merge.

2018-05-29 20:55 UTC, zippy commented on dna/cointoss/cointoss.js
>  /* Holochain API */ var _core_remove=remove;remove=function(a,b){return checkForError("remove",_core_remove(a,b))};var _core_makeHash=makeHash;makeHash=function(a,b){return checkForError("makeHash",_
This line comes from the code that got moved into core around allowing the app designer to choose throwing errors or returning them.  We should remove this otherwise it will confuse folks.

2018-05-29 20:55 UTC, zippy commented on dna/cointoss/cointoss.js
> +  debug(
I think we should remove this mermaid debugging.  I don't think it adds anything to cointoss.

2018-05-30 01:33 UTC, merged

2018-05-30 01:34 UTC, philipbeadle commented
I merged it as I added travis to develop and it works fine

2018-05-30 10:04 UTC, lucksus commented
This PR was merged without approval. I only see @zippy requesting changes. We say in the Playbooklet that "Pull requests need approval of at least two other team members before they are allowed to be merged."

https://docs.google.com/document/d/1Pzs9aXk1eQfyMWbwDyHgCz6kiHs_FpHjscaZyUlpei8/edit

2018-05-30 13:28 UTC, ddd-mtl commented
I made the changes zippy requested on develop. Should I do a new pull request? It seems I can't add to this PR anymore now that it is merged.

2018-05-30 16:15 UTC, zippy commented
Just go ahead an merge it!

On Wed, May 30, 2018 at 9:28 AM, damien <notifications@github.com> wrote:

> I made the changes zippy requested on develop. Should I do a new pull
> request? It seems I can't add to this PR anymore now that it is merged.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/holochain/cointoss/pull/4#issuecomment-393161492>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAAN6_A7KPPLAiuXOmCJ3pVD-z0w3T7gks5t3p6GgaJpZM4USH8V>
> .
>